### ISSUE TITLE
Ability to have more than one definition

### ISSUE THREAD

**Issue by MebinAbraham** [ONSdigital/sdc-global-design-patterns#116]
### Expected behaviour
Definitions to behave independantly of each other.
### Actual behaviour
Automatically selects the last definition as the `active` one if there is more than 1 definition.

Clicking the `link` or using `Hide this` collapses accordion and selects last definition as `Selected`
### Screenshot
<img width="301" alt="screen shot 2018-06-25 at 11 45 22" src="https://user-images.githubusercontent.com/35296336/41846005-4708bc42-786d-11e8-8681-d87de5b57105.png">

**Comment by armstrongb** [comment]
Low (ish) priority bug fix as currently low likelihood of multiple definitions per page being implemented.
