### ISSUE TITLE
When the title of a definition wraps on a new line it should indent inline with the first line of the title

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/sdc-global-design-patterns#117]
When the title of a definition wraps on a new line it should indent inline with the first line of the title

It's wrapping with no indentation 

Create a long title or reduce the browser window

<img width="397" alt="screen shot 2018-06-27 at 11 32 41" src="https://user-images.githubusercontent.com/8184622/41969490-79280848-79ff-11e8-9dfd-12c962355f66.png">

**Comment by armstrongb** [comment]
Resolved in previous release.
