### ISSUE TITLE
Change link in accordion cut off.

### ISSUE THREAD

**Issue by MebinAbraham** [ONSdigital/sdc-global-design-patterns#148]
### Expected behaviour
Not to be cut off.
### Actual behaviour
<img width="594" alt="screen shot 2018-08-16 at 09 16 08" src="https://user-images.githubusercontent.com/35296336/44196893-1dcb4700-a135-11e8-8646-11ab8c8bcaaf.png">

### Steps to reproduce the behaviour
Try any survey with the new collapisible summary design.

**Comment by armstrongb** [comment]
@MebinAbraham can you provide browser and platform details?

**Comment by boxadesign** [comment]
This is an implementation issue with the grid for the summary. So this can be closed.
