### ISSUE TITLE
Padding missing between calls to actions on the timeout modal

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/sdc-global-design-patterns#151]
There should be 1 rem (18px) of padding between the primary action and the secondary action

No padding between the buttons

Click on the link https://sdc-global-design-patterns.netlify.com/components/preview/timeout.html

Google Chrome Version 68.0.3440.106

Mac OS High Sierra

https://sdc-global-design-patterns.netlify.com/components/preview/timeout.html
<img width="866" alt="screen shot 2018-08-23 at 10 23 32" src="https://user-images.githubusercontent.com/8184622/44517159-d574d180-a6be-11e8-9c45-781efa4f26a2.png">

**Comment by armstrongb** [comment]
`u-mb-s` class needed on the Continue button.
