### ISSUE TITLE
Skip to content missing & cannot tab through site when logged in

### ISSUE THREAD

**Issue by emilioward** [ONSdigital/sdc-global-design-patterns#154]
### Expected behaviour
When tabbing through frontstage the skip to content banner is now missing which was available on earlier versions

### Actual behaviour
When tabbing nothing appears letting the user skip to their content. Also now cannot tab through frontstage when signed in 

### Steps to reproduce the behaviour
Load Safari 11 on Mac OS High Sierra on sign in try to tab and the banner doesn't appear, also try to tab when signed in and the tab never goes to the content

#### Browser
Safari 11

#### Operating System
Mac OS High Sierra

### Screenshot
Expected to look like below:
![screen shot 2018-08-24 at 09 47 01](https://user-images.githubusercontent.com/16239750/44575035-fb63aa00-a782-11e8-9eaf-c1f027cfddac.png)

**Comment by armstrongb** [comment]
@emilioward are you using `alt+tab`?

**Comment by emilioward** [comment]
Yes you're right I didnt realise that was how tabbing worked in safari. I'll close the issue
