### ISSUE TITLE
Show Password not working on safari for iOS

### ISSUE THREAD

**Issue by shahi645** [ONSdigital/sdc-global-design-patterns#157]
### Expected behaviour
Clicking `Show Password` reveals password

### Actual behaviour
Does not reveal password when clicked

### Steps to reproduce the behaviour
Launch frontstage using safari on any iOS device

### Technical information
iOS 9 used to test

#### Browser
Safari Mobile

#### Operating System
iOS

### Screenshot
<img width="467" alt="screen shot 2018-08-28 at 09 27 17" src="https://user-images.githubusercontent.com/22025926/44710767-ca49e900-aaa4-11e8-95d1-f3a2e8a31577.png">

**Comment by armstrongb** [comment]
@saedwards this could be related to the textbox .js update deployed in 1.5.3. iOS 9 Safari console is complaining about line `bundle.js:8780`
with `TypeError: limitedInputs.forEach is not a function. (In 'limitedInputs.forEach', 'limitedInputs.forEach' is undefined)`

Does not appear to complain in Chrome, Firefox or Safari on OS X at the moment.

Can be tested on localhost of `master` via browserstack.

**Comment by armstrongb** [comment]
Running a local v1.5.2 doesn't exhibit the same error.

It does however leave the password input failing silently in iOS 9 when toggling the password display.

**Comment by armstrongb** [comment]
May be an ES6 incompatibility so @saedwards to investigate transpiling to ES5.

/cc @shahi645

**Comment by saedwards** [comment]
I could replicate this issue in IE, which has no support for forEach methods on NodeLists, which are returned from querySelectorAll. Using jQuery would eliminate all these varying implementation issues and is certainly the most sensible approach.

**Comment by armstrongb** [comment]
@saedwards is it fixable in its current form without resorting to jQuery?
