### ISSUE TITLE
Mutually exclusive dropdown does not clear checkbox

### ISSUE THREAD

**Issue by bameyrick** [ONSdigital/sdc-global-design-patterns#191]
### Expected behaviour
If the checkbox is checked and then the user selects an option from the dropdown the checkbox should be cleared.

### Actual behaviour
The checkbox remains checked.

### Steps to reproduce the behaviour
Pull down `2454-ensure-units-on-text-inputs-can-scale-for-translations` branch on the `eq-survey-runner` repo and start the "test mutually exclusive" survey.

**Comment by armstrongb** [comment]
Closed in release v1.8.1.
