### ISSUE TITLE
Beta and feedback component grid.

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/sdc-global-design-patterns#197]
### Expected behaviour
1. The feedback and beta badge align to the left hand edge of the grid.
2. The textarea matches the main content column width.
3. Border uses `$color-border`

### Actual behaviour
Currently the feedback form is out of alignment. (Screenshot below.)

### Steps to reproduce the behaviour
Preview survey in pre-prod and use the feedback form above the footer.

#### Browser
All
#### Operating System
All

### Screenshot
![eq-preprod-feedbackandbeta-grid](https://user-images.githubusercontent.com/22910336/47503296-a9fa9880-d861-11e8-8a44-a9d87c14aa44.png)

**Comment by armstrongb** [comment]
reported by @will-madebymoon

**Comment by armstrongb** [comment]
Linked to https://github.com/ONSdigital/eq-survey-runner/issues/1885

**Comment by boxadesign** [comment]
@armstrongb I think this can be closed with the latest work happening on the feedback placement.

P.S this was implemented intentionally like this as the `beta` element is separate to the `feedback`. I think the issue raised probably has a point though!

**Comment by boxadesign** [comment]
This can be closed as the beta bar is replacing this...
https://github.com/ONSdigital/sdc-global-design-patterns/pull/214
