### ISSUE TITLE
Date range block

### ISSUE THREAD

**Issue by will-madebymoon** [ONSdigital/sdc-global-design-patterns#246]
The date range block in the implementation within runner is missing it's 'Period from' and 'Period to' labels. https://staging-runner.gcp.dev.eq.ons.digital/questionnaire/date-range-block/ . 
<img width="546" alt="Screenshot 2019-07-24 at 08 59 38" src="https://user-images.githubusercontent.com/8184622/61775742-671a2100-adf1-11e9-8a4d-c6f11e710a37.png">

**Comment by bameyrick** [comment]
This is more of an implementation issue in runner than a design system issue, so I've created a card on the trello board and will close this.
