### ISSUE TITLE
Yarn deploy broken

### ISSUE THREAD

**Issue by armstrongb** [ONSdigital/sdc-global-design-patterns#48]
The `yarn deploy` on `master` is currently generating the following error message when it is run.

> ➜  eq-survey-runner-patterns git:(master) yarn deploy
> yarn run v1.3.2
> $ gulp && yarn build && gh-pages -d dist
> Requiring external module babel-register
> /Users/local_user/projects/eq-survey-runner-patterns/node_modules/node-sass/lib/index.js:13
>     throw new Error(errors.unsupportedEnvironment());
>     ^
> 
> Error: Node Sass does not yet support your current environment: OS X 64-bit with Unsupported runtime (59)
> For more information on which environments are supported please see:
> https://github.com/sass/node-sass/releases/tag/v3.11.1
>     at Object.<anonymous> (/Users/local_user/projects/eq-survey-runner-patterns/node_modules/node-sass/lib/index.js:13:11)
>     at Module._compile (module.js:660:30)
>     at Module._extensions..js (module.js:671:10)
>     at Object.require.extensions.(anonymous function) [as .js] (/Users/benarmstrong/projects/eq-survey-runner-patterns/node_modules/babel-register/lib/node.js:152:7)
>     at Module.load (module.js:573:32)
>     at tryModuleLoad (module.js:513:12)
>     at Function.Module._load (module.js:505:3)
>     at Module.require (module.js:604:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (/Users/local_user/projects/eq-survey-runner-patterns/node_modules/gulp-sass/index.js:187:21)
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

On node `v9.3.0`

**Comment by hamishtaplin** [comment]
@armstrongb I find the error `Error: Node Sass does not yet support your current environment:` is usually because you've switched Node versions and not reinstalled with `yarn`. Can you confirm that's not the case?

**Comment by armstrongb** [comment]
@hamishtaplin thanks - I've just swapped to node 8.9.3 and it has corrected itself, so yes it looks like a reinstall of node with yarn might have been in order.

**Comment by armstrongb** [comment]
Closing this issue
