### ISSUE TITLE
Border on Currency / Unit form field cut off

### ISSUE THREAD

**Issue by jonnyshaw89** [ONSdigital/sdc-global-design-patterns#77]
### 
Expected behaviour
The border should not be cut off

### Actual behaviour
The border is cut off

### Screenshot
![img_e2aaa9f05272-1](https://user-images.githubusercontent.com/7594012/37346972-b5d18aba-26c8-11e8-94b9-65154e495bc0.jpeg)
![img_1800](https://user-images.githubusercontent.com/7594012/37346945-a15040a4-26c8-11e8-8bb0-8ab1765c2db0.PNG)

**Comment by MIslam92** [comment]
Same issue with iPhone 8
